### ISSUE TITLE
Thiếu file .editorconfig và .gitignore

### ISSUE THREAD

**Issue by laicasaane** [syusyugenz/baitap#1]
Đường link tải 2 file này có ghi trong đề bài. Cần đọc kĩ đề.

**Comment by laicasaane** [comment]
Sau khi bỏ file `.gitignore` vào đúng chỗ thì cần xoá thư mục `obj` đi rồi commit lại. Những lần sau thư mục `obj` sẽ tự động bị loại khỏi repo, không xuất hiện trong danh sách có thể commit nữa.

**Comment by syusyugenz** [comment]
Đã fix trong commit cee3a2620899e60bc7a9c81bd77edbc196476b0b
